---
dynaconf_merge:
  true

global:
  task_argument_class_mapping:
    standardize: movies_etl.tasks.StandardizeDataTask
    curate: movies_etl.tasks.CurateDataTask
  movie_languages_filter: ["EN", "FR", "DE", "ES"]

development:
  data:
    raw:
      location: data-lake-raw-dev/movie_ratings
    standardized:
      table: iceberg.default.movie_ratings_standardized
    curated:
      table: iceberg.default.movie_ratings_curated

staging:
  data:
    raw:
      location: s3://data-lake-raw-staging/movie_ratings
    standardized:
      table: iceberg.standardized_staging.movie_ratings
    curated:
      table: iceberg.curated_staging.movie_ratings

live:
  data:
    raw:
      location: s3://data-lake-raw-live/movie_ratings
    standardized:
      table: iceberg.standardized_live.movie_ratings
    curated:
      table: iceberg.curated_live.movie_ratings
