---
dynaconf_merge:
  true

global:
  task_argument_class_mapping:
    standardize: movies_etl.tasks.StandardizeDataTask
    curate: movies_etl.tasks.CurateDataTask
  movie_languages_filter: ["EN", "FR", "DE", "ES"]

development:
  data:
    raw:
      location: data-lake-raw-dev/movie_ratings
    standardized:
      table: default.movie_ratings_standardized
      dq_checks_file: movies_etl/tasks/standardize_data/dq_checks_standardized.yaml
    curated:
      table: default.movie_ratings_curated
      dq_checks_file: movies_etl/tasks/curate_data/dq_checks_curated.yaml

staging:
  data:
    raw:
      location: s3://data-lake-raw-staging/movie_ratings
    standardized:
      table: standardized_staging.movie_ratings
      dq_checks_file: dq_checks_standardized.yaml
    curated:
      table: curated_staging.movie_ratings
      dq_checks_file: dq_checks_curated.yaml

live:
  data:
    raw:
      location: s3://data-lake-raw-live/movie_ratings
    standardized:
      table: standardized_live.movie_ratings
      dq_checks_file: dq_checks_standardized.yaml
    curated:
      table: curated_live.movie_ratings
      dq_checks_file: dq_checks_curated.yaml
