---
dynaconf_merge:
  true

development:
  data:
    raw:
      location: data-lake-raw-dev/movie_ratings
    curated:
      table: default.movie_ratings_curated
      location: data-lake-curated-dev

staging:
  data:
    raw:
      location: s3://data-lake-raw-staging/movie_ratings
    curated:
      table: curated_staging.movie_ratings
      location: s3://data-lake-curated-staging

live:
  data:
    raw:
      location: s3://data-lake-raw-live/movie_ratings
    curated:
      table: curated_live.movie_ratings
      location: s3://data-lake-curated-live
