---
dynaconf_merge:
  true

development:
  data:
    path_raw: data-lake-dev/movie_ratings_raw
    path_curated: data-lake-dev/movie_ratings_curated

staging:
  data:
    path_raw: s3://data-lake-staging/movie_ratings_raw
    path_curated: s3://data-lake-staging/movie_ratings_curated

live:
  data:
    path_raw: s3://data-lake-live/movie_ratings_raw
    path_curated: s3://data-lake-live/movie_ratings_curated
