data_lake:
  raw: file:///home/movies/data_lake/raw
  standardised: file:///home/movies/data_lake/standardised
  curated: file:///home/movies/data_lake/curated

task_argument_class_mapping:
  ingest: movies_etl.tasks.ingest_data_task.IngestDataTask
  transform: movies_etl.tasks.transform_data_task.TransformDataTask
