data_repository:
  uri_prefix: file:///
  source_data: /home/movies/movies_data_repository/source
  directory_staging: /home/movies/movies_data_repository/staging
  directory_final: /home/movies/movies_data_repository/final

slack:
  token:
  channel:
  username:

spark:
  app_name: movies_etl
  log_level: ERROR
  partition_overwrite_mode: dynamic
  python_packages:
  - moviesetl.zip
  - packages.zip
  jars:
#  - com.amazonaws:aws-java-sdk:1.7.4
#  - org.apache.hadoop:hadoop-aws:2.7.6

task_argument_class_mapping:
  ingest: moviesetl.tasks.ingest_data_task.IngestDataTask
  transform: moviesetl.tasks.transform_data_task.TransformDataTask
