s3:
  bucket: etl-tests-guido
  source_file: movies.json
  directory_staging: movies_staging
  directory_final: movies_agg
  aws_key:
  aws_secret:

slack:
  token: test_token
  channel: test_channel
  username: test_username

spark:
  app_name: movies_etl
  master: local[*]
  executors:
    instances: 2
    cores: '2'
    memory: 6g
  default_parallelism: 20
  shuffle_partitions: 20
  log_level: ERROR
  python_packages:
  - programs.zip
  - packages.zip
  jars:
  - com.amazonaws:aws-java-sdk:1.7.4
  - org.apache.hadoop:hadoop-aws:2.7.6

task_argument_class_mapping:
  ingest: programs.tasks.ingest_data_task.IngestDataTask
  transform: programs.tasks.transform_data_task.TransformDataTask
