data_lake:
  source: file:///home/movies/data_lake/source
  staging: file:///home/movies/data_lake/staging
  final: file:///home/movies/data_lake/final

task_argument_class_mapping:
  ingest: moviesetl.tasks.ingest_data_task.IngestDataTask
  transform: moviesetl.tasks.transform_data_task.TransformDataTask
