version: "2"

services:
  movies_etl:
    image: movies_etl
    container_name: "movies_etl"
    build: .
    volumes:
    # volume to share local code folder with container, so we can make changes while developing
      - ".:/home/movies"
