---
dynaconf_merge:
  true

global:
  task_argument_class_mapping:
    ingest: spark_movies_etl.tasks.task_ingest_data.IngestDataTask
    transform: spark_movies_etl.tasks.task_transform_data.TransformDataTask
  movies_regions: ["FR", "US", "GB", "RU", "HU", "DK", "ES"]
  movies_max_reissues: 5

development:
  data_lake:
    bronze:
      base_path: data-lake-bronze-dev
      dataset: movies
    silver:
      table: default.movies_silver
    gold:
      table: default.movies_gold

staging:
  data_lake:
    bronze:
      base_path: s3://data-lake-bronze-staging
      dataset: movies
    silver:
      table: silver_staging.movies
    gold:
      table: gold_staging.movies


live:
  data_lake:
    bronze:
      base_path: s3://data-lake-bronze-live
      dataset: movies
    silver:
      table: silver_live.movies
    gold:
      table: gold_live.movies
