---
dynaconf_merge:
  true

global:
  task_argument_class_mapping:
    ingest: spark_movies_etl.tasks.task_ingest_data.IngestDataTask
    transform: spark_movies_etl.tasks.task_transform_data.TransformDataTask
  movies_regions: ["FR", "US", "GB", "RU", "HU", "DK", "ES"]
  movies_max_reissues: 5

development:
  data_lake:
    bronze: data_lake/bronze/movies
    silver: data_lake/silver/movies
    gold: data_lake/gold/movies

live:
  data_lake:
    bronze: s3://datalake-bronze/movies
    silver: s3://datalake-silver/movies
    gold: s3://datalake-gold/movies
