---
dynaconf_merge:
  true

global:
  task_argument_class_mapping:
    ingest: spark_movies_etl.tasks.task_ingest_data.IngestDataTask
    transform: spark_movies_etl.tasks.task_transform_data.TransformDataTask
  movies_regions: ["FR", "US", "GB", "RU", "HU", "DK", "ES"]
  movies_max_reissues: 5

development:
  data_lake:
    raw:
      base_path: data-lake-raw-dev
      dataset: movies
    standardized:
      table: default.movies_standardized
    curated:
      table: default.movies_curated

staging:
  data_lake:
    raw:
      base_path: s3://data-lake-raw-staging
      dataset: movies
    standardized:
      table: standardized_staging.movies
    curated:
      table: curated_staging.movies

live:
  data_lake:
    raw:
      base_path: s3://data-lake-raw-live
      dataset: movies
    standardized:
      table: standardized_live.movies
    curated:
      table: curated_live.movies
