---
dynaconf_merge:
  true

global:
  task_argument_class_mapping:
    ingest: movies_etl.tasks.task_ingest_data.IngestDataTask
    transform: movies_etl.tasks.task_transform_data.TransformDataTask
  movies_regions: ["FR", "US", "GB", "RU", "HU", "DK", "ES"]
  movies_max_reissues: 5

development:
  data_lake:
    raw: file:///Users/gk/Git/spark-movies-etl/data_lake/raw/movies
    standardised: file:///Users/gk/Git/spark-movies-etl/data_lake/standardised/movies
    curated: file:///Users/gk/Git/spark-movies-etl/data_lake/curated/movies

live:
  data_lake:
    raw: s3a://datalake-raw/movies
    standardised: s3a://datalake-standardised/movies
    curated: s3a://datalake-curated/movies
