---
dynaconf_merge:
  true

global:
  task_argument_class_mapping:
    ingest: movies_etl.tasks.task_ingest_data.IngestDataTask
    transform: movies_etl.tasks.task_transform_data.TransformDataTask
  movies_regions: ["FR", "US", "GB", "RU", "HU", "DK", "ES"]
  movies_max_reissues: 5

development:
  data_lake:
    raw: data_lake/bronze/movies
    standardised: data_lake/silver/movies
    curated: data_lake/gold/movies

live:
  data_lake:
    raw: s3a://datalake-bronze/movies
    standardised: s3a://datalake-silver/movies
    curated: s3a://datalake-gold/movies
