name: CI/CD - PR

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: make setup

    - name: Run code checks
      run: make code-checks

    - name: Run tests
      run: make test

  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build application
      run: make build

    # # Leave S3 release commented out since it's not a production repo
    # - name: Release to S3
    #   run: aws s3 sync --delete ${SOURCE_DIR} s3://${AWS_S3_BUCKET}/${DEST_DIR}
    #   env:
    #     AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
    #     AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    #     AWS_REGION: eu-west-1
    #     AWS_S3_BUCKET: movies-binaries
    #     SOURCE_DIR: deps
    #     DEST_DIR: "spark-movies-etl/PR-${{ github.event.pull_request.number }}"
