name: CI/CD - PR

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }} - ${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: make setup

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test

  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: make setup

    - name: Build
      run: make docker-build

    # TO DO: push docker image to ECR with tag `spark-movies-etl:PR-<pr-number>`
