name: CI/CD - PR workflow
on:
  pull_request:
    branches: [ master ]
jobs:
  ci-cd-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: make setup
    - name: Run code checks
      run: make code-checks
    - name: Run tests
      run: make test
    - name: Build application
      run: make build
    # Leave S3 release commented out since it's not a production repo
    # - name: Release to S3
    #   uses: jakejarvis/s3-sync-action@v0.5.1
    #   with:
    #     args: --delete
    #   env:
    #     AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
    #     AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    #     AWS_S3_BUCKET: movies-binaries
    #     AWS_REGION: eu-west-1
    #     SOURCE_DIR: deps
    #     DEST_DIR: "spark-movies-etl/PR-${{ github.event.pull_request.number }}"
