name: CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test-build-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: make setup
    - name: Run code checks
      run: make pre-commit
    - name: Run tests
      run: make test
    - name: Build application
      run: make build
    - name: Get package version
      run: echo "PACKAGE_VERSION=$(poetry version --short)" >> $GITHUB_ENV
    - name: Create Github release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      if: ${{ github.event_name == 'push' }}
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "${{ env.PACKAGE_VERSION }}"
        files: deps/*
    # TODO: release to S3
